eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9999
spring:
  application:
    name: gateway
zuul:
  prefix: /ms
  routes:
    greet:
      path: /api1/**
      serviceId: greet-api
    welcome:
      path: /api2/**
      serviceId: welcome-api